language: php

php:
  - 5.6
  - hhvm
  - 7.0

before_script:
  - composer install
  - composer update #required to install zend-servicemanager and zend-barcode

script:
  - mkdir -p build/logs 
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
